TARGET = main
all:
	gcc -o $(TARGET) part2.c
	$(info Program has been compiled as $(TARGET) output file)
	$(info please run ./$(TARGET) {P} {M} as parameters)

clean:
	rm $(TARGET)
	$(info Binary files has been cleaned from this directory)
