TARGET = ass1
all:
	gcc -o $(TARGET) ass1.c
	$(info Program has been compiled as $(TARGET) output file)
	$(info please run ./$(TARGET) {L} {N} as parameters)

clean:
	rm $(TARGET)
	$(info Binary files has been cleaned from this directory)
